language: c

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

matrix:
  include:
    - env: GAPBRANCH=master ABI=64
    - env: GAPBRANCH=master ABI=32
      addons:
        apt_packages:
          - libgmp-dev:i386
          - libreadline-dev:i386
          - zlib1g-dev:i386
          - gcc-multilib
          - g++-multilib
    - env: GAPBRANCH=master
      os: osx
    - env: GAPBRANCH=stable-4.9
    - env: GAPBRANCH=stable-4.10

branches:
  only:
    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
